# application.yml
spring:
  application:
    name: ship-backend-app
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        format: YAML
        data-key: token
        profile-separator: ','
        watch:
          enabled: true
      discovery:
        prefer-ip-address: true
        ip-address: 192.168.31.75
        service-name: ship-backend-app
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import: "consul:"
  profiles:
    active: dev
logging:
  level:
    org:
      springframework:
        cloud:
          consul: DEBUG
        boot:
          actuate:
            endpoint: DEBUG